name: Build for iOS

on:
  [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "Build for iOS"

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          brew install meson pkg-config
          mkdir -p /tmp/build/{include/{EGL,KHR},lib/pkgconfig}
          cp libdrm.pc /tmp/build/lib/pkgconfig/
          cd /tmp/build/include
          wget https://github.com/khanhduytran0/libepoxy/raw/master/include/EGL/eglplatform.h -P EGL
          wget https://github.com/khanhduytran0/libepoxy/raw/master/include/KHR/khrplatform.h -P KHR
      - name: Build libepoxy
        run: |
          git clone --depth 1 https://github.com/khanhduytran0/libepoxy.git
          cd libepoxy
          meson "build-ios-aarch64" \
            --prefix=/tmp/build \
            --cross-file "../ios-aarch64" \
            -Degl=yes -Dglx=no -Dx11=false -Dtests=false
          ninja -C "build-ios-aarch64" install
      - name: Build virglrenderer
        run: |
          meson "build-ios-aarch64" \
            --prefix=/tmp/build \
            --cross-file "ios-aarch64" \
            -Dplatforms=egl
          ninja -C "build-ios-aarch64" install
          cp "build-ios-aarch64/vtest/libvirgl_test_server.dylib" /tmp/build/lib/
      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: /tmp/build
